name:                purfx
version:             0.1.0.0
git:                 "aufarg/purfx"
license:             BSD3
author:              "Aufar Gilbran"
maintainer:          "aufargilbran@gmail.com"
description:         Please see the README on GitHub at <https://github.com/aufarg/purfx#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec >= 3.0 && < 4
- mtl
- llvm-hs
- llvm-hs-pure
- bytestring
- optparse-applicative

library:
  source-dirs: src

executables:
  pfc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ld-options: -fuse-ld=lld -static
    dependencies:
    - purfx
